"""docs/ASSUMPTIONS.md, generated from oci/config.py (SPEC §18.1, §20.1). Never hand-edit the output."""
from __future__ import annotations

import pathlib

from oci.config import CONFIG

REGISTER = [
    ("A1", "Covariance fitted from public CDM datasets, applied to TLE-derived states (until the Kelvins fit lands: DECLARED per-object σ)", "MODELLED", "Pc values shift; relative rankings are more robust than absolute values"),
    ("A2", f"Hard-body radius default {CONFIG.pc.hard_body_radius_m} m combined where dimensions unknown", "MODELLED", "Pc scales roughly with HBR; affects thresholds crossed"),
    ("A3", "Mass estimated from object class and RCS size bucket", "MODELLED", "Affects hazard index, not burden"),
    ("A4", f"Manoeuvre triggered when Pc exceeds the declared threshold ({CONFIG.thresholds.declared_pc_threshold:g}, IADC)", "MODELLED", "Burden counts scale by orders of magnitude with threshold. Always stated."),
    ("A5", "Δv per CAM derived from required miss-distance clearance (bisection, along-track/radial/normal, best reported)", "MODELLED", "Δv totals shift; ordering largely preserved"),
    ("A6", "Intra-constellation conjunctions excluded from imposed burden", "STATED", "Including them would make mega-constellations rank first for modelling reasons"),
    ("A7", f"Attribution rules {list(CONFIG.attribution.rules)} in headline figures (dead→active is unambiguous)", "STATED", "Active–active flows flagged contested, never silently split"),
    ("A8", f"Decay lifetime from a static exponential atmosphere, {CONFIG.atmosphere.solar_condition}", "MODELLED", "Solar-cycle variation not modelled; lifetimes at 500–700 km can be off by a factor"),
    ("A9", "PMD success rate as entered by the user (capacity engine)", "STATED", "Dominates long-horizon hazard"),
    ("A10", f"Implied fee calibrated from {CONFIG.fee.calibration}", "INDICATIVE", "Not a price. An illustration of magnitude."),
    ("A11", "OCS is our own prototype metric, anchored to the published 10 CAM/month viability threshold", "PROTOTYPE", "Not an industry standard. Components always shown."),
    ("A12", "Monte Carlo robustness = fraction of simulated scenarios remaining below Pc* under A1", "MODELLED", "Not prediction accuracy. Never called that."),
    ("A13", "SGP4 propagation, general-perturbations accuracy, TEME frame throughout", "STATED", "Kilometre-scale error at 72 h; unsuitable for operational decisions"),
    ("A14", "Lethal non-trackable debris not modelled", "STATED", "True risk is higher than computed; burden figures are lower bounds"),
    ("A15", f"Screening: {CONFIG.screening.screening_volume_m:.0f} m volume, {CONFIG.screening.coarse_step_min*60:.0f} s sample step, spatial index per sample, parabolic-dip gate", "STATED", "A 15-minute step was measured to miss crossing conjunctions; see oci/physics/screen.py"),
    ("A16", f"Station-keeping budgets by altitude band {CONFIG.mission.sk_budget_mps_per_day} m/s/day", "MODELLED", "Mission-days scale inversely with budget"),
    ("A17", f"Uncertainty shrinkage σ(τ): λ = {CONFIG.voi.lambda_per_h}/h, floor {CONFIG.voi.sigma_floor_fraction} ({CONFIG.voi.source})", "MODELLED", "Drives VoI; replaced by the Kelvins fit"),
]


def write_assumptions_doc(path: str | pathlib.Path = "docs/ASSUMPTIONS.md") -> pathlib.Path:
    a = CONFIG.assumptions_block()
    lines = ["# Assumptions register", "",
             "Generated by `python -m oci assumptions` from `oci/config.py`. Every value here is displayed in the UI and embedded in every export (SPEC §18.1).", "",
             "## Current assumption block (API envelope)", "", "| key | value |", "|---|---|"]
    lines += [f"| `{k}` | `{v}` |" for k, v in a.items()]
    lines += ["", "## Register", "", "| # | Assumption | Label | Impact if wrong |", "|---|---|---|---|"]
    lines += [f"| {i} | {t} | **{l}** | {imp} |" for i, t, l, imp in REGISTER]
    lines += ["", "## Operator thresholds (D6)", "", "| actor | Pc trigger | source |", "|---|---|---|"]
    lines += [f"| {k} | {v:g} | {CONFIG.thresholds.sources.get(k, '')} |" for k, v in CONFIG.thresholds.per_operator.items()]
    lines += ["", "## Validator constraints (M9)", "", "| id | constraint | default |", "|---|---|---|",
              f"| C1 | max Δv per burn | {CONFIG.validator.dv_max_per_burn_mps} m/s |",
              f"| C2 | remaining propellant | {CONFIG.validator.remaining_dv_mps} m/s |",
              f"| C3 | command uplink lead | {CONFIG.validator.uplink_lead_min} min |",
              f"| C4 | minimum manoeuvre lead before TCA | {CONFIG.validator.min_maneuver_lead_min} min |",
              f"| C5 | post-burn perigee floor | {CONFIG.validator.min_alt_km} km |",
              f"| C6 | mission box | ±{CONFIG.validator.mission_alt_band_km} km, ±{CONFIG.validator.mission_inc_band_deg}° |",
              f"| C7 | post-burn re-screen | no new conjunction ≥ Pc* or < {CONFIG.validator.min_miss_floor_m:.0f} m in {CONFIG.decision.horizon_h:.0f} h |",
              f"| C8 | eclipse / power | burn in eclipse allowed: {CONFIG.validator.eclipse_burn_allowed} |",
              f"| C9 | slew time | {CONFIG.validator.slew_time_min} min |",
              "| C10 | COORDINATE: both partners' constraints | individually satisfied |", ""]
    out = pathlib.Path(path)
    out.write_text("\n".join(lines))
    return out
